# Generated by Django 4.1.2 on 2022-12-08 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CittaMetropolitana',
            fields=[
                ('codice_cittametropolitana', models.IntegerField(primary_key=True, serialize=False, verbose_name='codice Istat')),
                ('name', models.CharField(db_index=True, max_length=300, verbose_name='nome')),
            ],
            options={
                'verbose_name': 'città metropolitana',
                'verbose_name_plural': 'città metropolitane',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Regione',
            fields=[
                ('codice_regione', models.IntegerField(primary_key=True, serialize=False, verbose_name='codice Istat')),
                ('name', models.CharField(db_index=True, max_length=300, verbose_name='nome')),
            ],
            options={
                'verbose_name': 'regione',
                'verbose_name_plural': 'regioni',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('codice_provincia', models.IntegerField(primary_key=True, serialize=False, verbose_name='codice Istat')),
                ('name', models.CharField(db_index=True, max_length=300, verbose_name='Nome')),
                ('codice_targa', models.CharField(db_index=True, max_length=2)),
                ('regione', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comuni_italiani.regione')),
            ],
            options={
                'verbose_name': 'provincia',
                'verbose_name_plural': 'province',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Comune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice_istat', models.IntegerField(db_index=True, unique=True, verbose_name='codice Istat')),
                ('codice_catastale', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('name', models.CharField(db_index=True, max_length=300, verbose_name='nome')),
                ('is_capoluogo', models.BooleanField(default=False, verbose_name='capoluogo')),
                ('altitudine', models.IntegerField(blank=True, null=True)),
                ('superficie', models.FloatField(blank=True, null=True, verbose_name='superficie (kmq)')),
                ('popolazione', models.IntegerField(blank=True, null=True)),
                ('citta_metropolitana', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='comuni_italiani.cittametropolitana')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comuni_italiani.provincia')),
            ],
            options={
                'verbose_name': 'comune',
                'verbose_name_plural': 'comuni',
                'ordering': ['name'],
            },
        ),
    ]
