# Generated by Django 4.1.2 on 2022-12-08 11:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('comuni_italiani', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Azienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ragione_sociale', models.CharField(default='', max_length=255)),
                ('partita_iva', models.CharField(default='', max_length=11)),
                ('bilancio_depositato_2020', models.FileField(default='', upload_to='')),
                ('bilancio_depositato_2021', models.FileField(default='', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='DatiComune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pef_mis_o_ric', models.CharField(choices=[('CALCOLATO', 'CALCOLATO'), ('MISURATO', 'MISURATO')], default='', max_length=16)),
                ('ris_ula_o_ore', models.CharField(choices=[('ULA', 'ULA'), ('ORE LAVORATE', 'ORE LAVORATE')], default='', max_length=16)),
                ('tot_app', models.FloatField(default=0)),
                ('app_servizi', models.FloatField(default=0)),
                ('app_rifiuti_diff', models.FloatField(default=0)),
                ('app_rifiuti_indiff', models.FloatField(default=0)),
                ('app_igiene', models.FloatField(default=0)),
                ('altri_gestori_flag', models.BooleanField(default=False)),
                ('altri_gestori', models.CharField(blank=True, default='', max_length=512)),
                ('appalto_attuale_data', models.DateField(default='1970-01-01')),
                ('impresa_op_com_data', models.DateField(default='1970-01-01')),
                ('valore_can', models.FloatField(default=0)),
                ('adeg_contr_flag', models.BooleanField(default=False)),
                ('ricavi_conai_flag', models.BooleanField(default=False)),
                ('impresa_cts_flag', models.BooleanField(default=False)),
                ('impresa_ctr_flag', models.BooleanField(default=False)),
                ('spazz_e_ig_flag', models.BooleanField(default=False)),
                ('serv_exra_arera_flag', models.BooleanField(default=False)),
                ('serv_exra_arera', models.CharField(blank=True, default='', max_length=512)),
                ('lav_in_corso_flag', models.BooleanField(default=False)),
                ('lav_in_corso', models.CharField(blank=True, default='', max_length=512)),
                ('var_gest_flag', models.BooleanField(default=False)),
                ('var_gest', models.CharField(blank=True, default='', max_length=512)),
                ('miglior_qual_flag', models.BooleanField(default=False)),
                ('miglior_qual', models.CharField(blank=True, default='', max_length=512)),
                ('costi_tqrif_flag', models.BooleanField(default=False)),
                ('costi_tqrif', models.FloatField(default=0)),
                ('ton_totali', models.FloatField(default=0)),
                ('ton_anno_1', models.FloatField(default=0)),
                ('ton_anno_2', models.FloatField(default=0)),
                ('ton_anno_3', models.FloatField(default=0)),
                ('xcent_raccolta_diff', models.FloatField(default=0)),
                ('xcent_raccolta_anno_1', models.FloatField(default=0)),
                ('xcent_raccolta_anno_2', models.FloatField(default=0)),
                ('xcent_raccolta_anno_3', models.FloatField(default=0)),
                ('xcent_media_imp', models.FloatField(default=0)),
                ('xcent_media_imp_org', models.FloatField(default=0)),
                ('xcent_media_imp_cart', models.FloatField(default=0)),
                ('xcent_media_imp_plastica', models.FloatField(default=0)),
                ('xcent_media_imp_metallo', models.FloatField(default=0)),
                ('xcent_media_imp_vetro', models.FloatField(default=0)),
                ('sent', models.BooleanField(default=0)),
                ('azienda', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='core.azienda')),
                ('comune', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='comuni_italiani.comune')),
            ],
        ),
        migrations.CreateModel(
            name='CostoSmaltimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imp_smalt', models.CharField(default='', max_length=255)),
                ('tipo_rifiuto', models.CharField(default='', max_length=255)),
                ('tipo_costo', models.CharField(choices=[('CTS', 'CTS'), ('CTR', 'CTR')], default='', max_length=3)),
                ('anno', models.CharField(choices=[('2020', '2020'), ('2021', '2021')], default='', max_length=4)),
                ('tons', models.FloatField(default='NULL')),
                ('prezzo_unitario', models.FloatField(default='NULL')),
                ('importo', models.FloatField(default='NULL')),
                ('daticomune', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.daticomune')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.CharField(max_length=200, unique=True)),
                ('email2', models.CharField(default='', max_length=200)),
                ('nome', models.CharField(default='', max_length=25)),
                ('cognome', models.CharField(default='', max_length=25)),
                ('password', models.CharField(max_length=200)),
                ('titolo', models.CharField(choices=[('ambiente', 'ambiente'), ('consulente', 'consulente'), ('amministrazione', 'amministrazione'), ('logistica', 'logistica')], default='', max_length=255)),
                ('ragione_sociale', models.CharField(default='', max_length=255)),
                ('p_iva', models.CharField(default='', max_length=11)),
                ('telefono', models.CharField(default='', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('azienda', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.azienda')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
