# Generated by Django 4.1.2 on 2022-12-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email2',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
