# Generated by Django 4.1.2 on 2022-12-09 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_email2'),
    ]

    operations = [
        migrations.AddField(
            model_name='azienda',
            name='ammortamenti',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='azienda',
            name='export_daticomuni',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='azienda',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.azienda'),
        ),
    ]
