# Generated by Django 4.1.2 on 2022-12-14 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_azienda_ammortamenti_azienda_export_daticomuni_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daticomune',
            old_name='sent',
            new_name='completed',
        ),
    ]
