# Generated by Django 4.1.2 on 2023-01-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_sent_daticomune_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='azienda',
            name='bilancio_depositato_2020',
        ),
        migrations.RemoveField(
            model_name='azienda',
            name='bilancio_depositato_2021',
        ),
        migrations.AddField(
            model_name='azienda',
            name='bilancio_depositato_anno1',
            field=models.FileField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='azienda',
            name='bilancio_depositato_anno2',
            field=models.FileField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='azienda',
            name='ammortamenti',
            field=models.FileField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
