# Generated by Django 4.1.2 on 2023-01-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_azienda_bilancio_depositato_2020_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='azienda',
            name='bilancio_depositato_anno1',
            field=models.FileField(default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='azienda',
            name='bilancio_depositato_anno2',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
    ]
