# Generated by Django 4.1.2 on 2023-01-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_azienda_bilancio_depositato_anno1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='azienda',
            name='ammortamenti',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='azienda',
            name='bilancio_depositato_anno1',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='azienda',
            name='export_daticomuni',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
    ]
