# Generated by Django 4.1.2 on 2023-01-10 19:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_azienda_ammortamenti_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 10, 20, 2, 2, 708870)),
        ),
    ]
