# Generated by Django 4.1.2 on 2023-01-10 19:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_request_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_assigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 10, 20, 55, 15, 109145)),
        ),
    ]
