# Generated by Django 4.1.2 on 2023-01-11 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_is_assigned_alter_user_request_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daticomune',
            name='ricavi_conai_flag',
        ),
        migrations.AddField(
            model_name='daticomune',
            name='ricavi_conai',
            field=models.CharField(choices=[('IMPRESA', 'IMPRESA'), ('COMUNE', 'COMUNE')], default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 11, 18, 18, 37, 697983)),
        ),
    ]
