# Generated by Django 4.1.2 on 2023-01-11 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_daticomune_ricavi_conai_flag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='azienda',
            name='pef_mis_o_ric',
            field=models.CharField(choices=[('CALCOLATO', 'CALCOLATO'), ('MISURATO', 'MISURATO')], default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 11, 18, 39, 25, 186979)),
        ),
    ]
