# Generated by Django 4.1.2 on 2023-01-12 15:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_azienda_pef_mis_o_ric_alter_user_request_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daticomune',
            name='ricavi_conai',
            field=models.CharField(choices=[('IMPRESA', 'IMPRESA'), ('COMUNE', 'COMUNE')], default='IMPRESA', max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 12, 16, 28, 12, 662648)),
        ),
    ]
