# Generated by Django 4.1.2 on 2023-01-15 16:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_daticomune_ricavi_conai_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='daticomune',
            name='cont_commessa_anno1',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='daticomune',
            name='cont_commessa_anno2',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='daticomune',
            name='contratto_appalto',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='daticomune',
            name='ultimo_pef',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='daticomune',
            name='azienda',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.azienda'),
        ),
        migrations.AlterField(
            model_name='daticomune',
            name='ris_ula_o_ore',
            field=models.CharField(blank=True, choices=[('ULA', 'ULA'), ('ORE LAVORATE', 'ORE LAVORATE')], default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 15, 17, 5, 29, 140165)),
        ),
    ]
