# Generated by Django 4.1.2 on 2023-01-20 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_azienda_report_attempts_azienda_report_is_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='azienda',
            name='ammortamenti',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='azienda',
            name='bilancio_depositato_anno1',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='azienda',
            name='bilancio_depositato_anno2',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='azienda',
            name='export_daticomuni',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='report',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 20, 19, 21, 10, 136767)),
        ),
        migrations.AlterField(
            model_name='user',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 20, 19, 21, 10, 133766)),
        ),
    ]
