# Generated by Django 4.1.2 on 2023-01-21 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_azienda_ammortamenti_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daticomune',
            name='cont_commessa_anno1',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='daticomune',
            name='cont_commessa_anno2',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='daticomune',
            name='contratto_appalto',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='daticomune',
            name='ultimo_pef',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='report',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 21, 18, 13, 28, 301697)),
        ),
        migrations.AlterField(
            model_name='user',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 21, 18, 13, 28, 298695)),
        ),
    ]
