# Generated by Django 4.1.2 on 2023-01-28 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_daticomune_cont_commessa_anno1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 28, 17, 42, 13, 622247)),
        ),
        migrations.AlterField(
            model_name='user',
            name='request_date',
            field=models.DateTimeField(default='28.01.2023 17:42:13'),
        ),
    ]
