# Generated by Django 4.1.2 on 2023-01-28 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_report_request_date_alter_user_request_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 28, 18, 25, 49, 766859)),
        ),
        migrations.AlterField(
            model_name='user',
            name='request_date',
            field=models.DateField(default='28.01.2023 18:25:49'),
        ),
    ]
