# Generated by Django 4.1.2 on 2023-02-03 22:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_report_request_date_alter_user_request_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='azienda',
            old_name='ammortamenti',
            new_name='cespiti',
        ),
        migrations.AlterField(
            model_name='report',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 3, 23, 45, 32, 600390)),
        ),
        migrations.AlterField(
            model_name='user',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 3, 23, 45, 32, 597392)),
        ),
    ]
