# Generated by Django 5.1.5 on 2025-01-14 16:36

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_rename_ammortamenti_azienda_cespiti_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daticomune',
            name='xcent_media_imp',
        ),
        migrations.RemoveField(
            model_name='daticomune',
            name='xcent_media_imp_cart',
        ),
        migrations.RemoveField(
            model_name='daticomune',
            name='xcent_media_imp_metallo',
        ),
        migrations.RemoveField(
            model_name='daticomune',
            name='xcent_media_imp_org',
        ),
        migrations.RemoveField(
            model_name='daticomune',
            name='xcent_media_imp_plastica',
        ),
        migrations.RemoveField(
            model_name='daticomune',
            name='xcent_media_imp_vetro',
        ),
        migrations.AddField(
            model_name='costosmaltimento',
            name='comuneSedeImpianto',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='costosmaltimento',
            name='gestore',
            field=models.CharField(choices=[('GESTORE', 'GESTORE'), ('COMUNE', 'COMUNE')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='costosmaltimento',
            name='gestoreImpianto',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='costosmaltimento',
            name='impiantoDestinazione',
            field=models.CharField(default=None, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='costosmaltimento',
            name='note',
            field=models.CharField(default=None, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='costosmaltimento',
            name='partitaIvaGestoreImpianto',
            field=models.CharField(default=None, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='costosmaltimento',
            name='tipoImpianto',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='daticomune',
            name='idArera',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_code',
            field=models.CharField(default=0, max_length=5),
        ),
        migrations.AddField(
            model_name='user',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='costosmaltimento',
            name='anno',
            field=models.CharField(choices=[('2022', '2022'), ('2023', '2023')], default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='report',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 14, 17, 36, 22, 794170)),
        ),
        migrations.AlterField(
            model_name='user',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 14, 17, 36, 22, 771193)),
        ),
        migrations.CreateModel(
            name='EfficienzaQualitaDifferenziata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consorzio', models.CharField(blank=True, max_length=1025)),
                ('pretrattamento', models.BooleanField(default=False)),
                ('quantita_in_ton', models.FloatField(default=0)),
                ('prefatture_a_2', models.CharField(blank=True, max_length=1024)),
                ('azienda', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.azienda')),
            ],
            options={
                'unique_together': {('azienda', 'consorzio')},
            },
        ),
    ]
