# Generated by Django 5.1.5 on 2025-01-15 10:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_daticomune_xcent_media_imp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daticomune',
            name='ultimo_pef',
        ),
        migrations.AlterField(
            model_name='report',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 15, 11, 44, 38, 769659)),
        ),
        migrations.AlterField(
            model_name='user',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 15, 11, 44, 38, 762668)),
        ),
    ]
