# Generated by Django 5.1.5 on 2025-01-15 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_daticomune_ultimo_pef_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daticomune',
            old_name='cont_commessa_anno1',
            new_name='cont_commessa_anno_2',
        ),
        migrations.RenameField(
            model_name='daticomune',
            old_name='cont_commessa_anno2',
            new_name='mud_a_1',
        ),
        migrations.AddField(
            model_name='daticomune',
            name='mud_a_2',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='daticomune',
            name='pef_valid_ETC_a_2',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='report',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 15, 15, 16, 25, 870591)),
        ),
        migrations.AlterField(
            model_name='user',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 15, 15, 16, 25, 861312)),
        ),
    ]
